language: node_js
node_js:
- '10.10'

deploy:
  provider: heroku
  app: chatbotxxxasd
  api_key:
    secure: a+sSW3mNHeXBK7Xw1HhKLVyunsoF7gPgexJcnvqLVihgRTNn+MplzoK9eteoUVFyOYJQZvTTbxqnnVM+k6g7OZZhhCciyEtlM905yVFpNmpbAzOTXfEgdgmUPlAEugavrviMDRA1Owf43SsHtDJ2550zJBMiKIvyb4PN4GSqhPjGxBNO4+8t2qNtE9ngYNu3awhK8heEuoFc7h2EvnOVUYc7Fz/EXtYyKX2tR2B5Z1F7xOLtGSzWCpQf9nkgYoUYVOTKSSHvkQunhqzL+JNUVRaX7DF9iC7UHm3jz3ow7MFtyMwahW7CTkIY+5zKamxhMs60A9oH57l4PI4N9Bl77lG8A6I2aCtjs3xxsF4Q2x/BA++sVBqN35NvXKuniRUzPg1jVMVmNZrT6/2LjcQidBYpPz566hcB+6ATR3pb7zxs4jxwKdd2CjMGVPkEq0HF8gNNeRns/K/CnCN12wcKcvraXsUJj3ue9CUtX16NpQzVfi/VhATula+WfEZ3SX3bPkfPsjyXCohAm6E2fn8LyEkqeyM5UKLxe/qBnOZMwDaM0DfEse1jyI9O+mGAlTMg5kLo4y1HWiJ0MqXwA4nAtGrD3nizQ2bBUonvc4NKz2/UyrhDHOE3rAVNaSUjCTKc6U3OLNRHR6xW3JB+q5HOkHi/MXCvQIxCu6twMYvkjso=
